### ISSUE TITLE
create label functions for variables and datasets

### ISSUE THREAD

**Issue by GForb** [GForb/prediction_for_autistic_children#26]
create two functions `label_var` and `label_data` that take as arguments stings containing variable names or the dataset names we use (eg. `"gui"`) and return full labels eg. "Growing Up in Ireland" or SDQ Total.

For label_var use the labels in the var_metadata and have an option to use label 1 or 2
for label_study include a column of labels in the study metadata. Study metadata is also needed for issue #21 

assume that the var_metadata object is loaded (have a second argument to the function as `metadata =  var_metadata`

Add simple, quick to run tests for the functions to the test folder.

When you've done this, running test() in the console should run all the test scripts.

**Comment by GForb** [comment]
Once you've created the label_var function incorperate into the summary table function and raincloud plot function so the name or axis labels use variable labels.

**Comment by levhor** [comment]
gordon i think we need to create a more extensive metadata file for this as the current file cannot label whether it's parent or teacher reported

**Comment by GForb** [comment]
At the moment can we stick with what we have and leave out whether it is parent or teacher report from the label. It is unlikely that an analysis will use data from a mixture of reporters ie. we'll aim to use exclusively parent or exclusively self report and the reporter can be covered in the methods/or any table/graph header or footer.

At the moment our focus in on primary parent report data and I'd like to avoid spending too much time on data from other reporters in case we don't end up using it.
